"use client";
import { magicClient } from "@/Lib/MagicLink";
import "./globals.css";
import { useState } from "react";

import AnimatedText from "@/Utils/AnimatedText";
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Netflix",

  description: "Generated by create next app",
  icons: {
    icon: "static/logo/netflix-icon.svg",
    apple: "static/logo/netflix-icon.svg",
  },
  Head: (
    <>
      <link
        rel="icon"
        href="static/logo/netflix-icon.svg"
        type="image/svg"
        sizes="<generated>"
      />
      <link
        rel="preconnect"
        href="https://fonts.googleapis.com"
      />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet"
      />
    </>
  ),
};

export default function RootLayout({ children }) {
  const [Isloading, setIsloading] = useState(true);
  const router = useRouter();

  const checklogstatus = async () => {
    // const Isloged = await magicClient?.user?.isLoggedIn();
    const Isloged = true;

    if (!Isloged) {
      router.push("/login");
      setTimeout(() => {
        setIsloading(false);
      }, 500);
    } else {
      setTimeout(() => {
        setIsloading(false);
      }, 500);
    }

    return () => {};
  };
  checklogstatus();
  return (
    <html lang="en">
      <body>{Isloading ? <AnimatedText Text="Netflix" /> : children}</body>
    </html>
  );
}
