// import "./globals.css";
import "./output.css";

import { Inter } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
 
import Loaderswitch from "@/Components/Loaderswitch";
export const metadata = {
  title: { default: "Netflix clone" },
  description: "Generated by create next app", 

  icons: {
    icon: '/icon.ico',
  }, 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Loaderswitch >{children}</Loaderswitch>
    </html>
  );
}
